### ISSUE TITLE
Add 18.1.c.0514-950-RB for VCNT-A

### ISSUE THREAD

**Issue by SmokeHound** [hack-technicolor/hack-technicolor#111]
**Important:** Please, check issue still occurs in [Latest](https://hack-technicolor.readthedocs.io/en/latest/) branch before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

18.1.c.0514-950-RB

## Device Info

Board Mnemonic: VCNT-A

Model Number: DJA0231

Vendor Name/Code: Telstra

## Where did you find it?

ISP RBI file link (if known):

- Protocol: 
- Link: 
- Restrictions (if any): 

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: 

## Did you manage to root this firmware version already?

- [ ] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [X] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [ ] Yes! I will take care of that
- [X] No, do it for me, I can't use GitHub...

**Comment by LuKePicci** [comment]
Done in 24a3ac3 Look here for the latest branch of the website: https://hack-technicolor.readthedocs.io/en/latest/Repository/
