### ISSUE TITLE
Add TC_VCNT-A_18.1.c.0514-950RB for DJA0231TLS

### ISSUE THREAD

**Issue by juzman** [hack-technicolor/hack-technicolor#112]
**Important:** Please, check firmware isn't already listed in [Latest branch](https://hack-technicolor.readthedocs.io/en/latest/Repository) before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

18.1.c.0514-2881009-20200602123158-950-RB

## Device Info

Board Mnemonic: VCNT-A

Model Number: DJA0231TLS

Vendor Name/Code: TLS

## Where did you find it? N/A

ISP RBI file link (if known): http://fwstore.bdms.telstra.net/Technicolor_vcnt-a_ACR-13-18.1.c.0514-950-RB/vcnt-a_ACR-13-18.1.c.0514-950-RB.rbi

- Protocol: HTTP
- Link: http://fwstore.bdms.telstra.net/Technicolor_vcnt-a_ACR-13-18.1.c.0514-950-RB/vcnt-a_ACR-13-18.1.c.0514-950-RB.rbi
- Restrictions (if any): Stock Firmware

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: File is too large (42MB)

## Did you manage to root this firmware version already?

- [x] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [ ] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [ ] Yes! I will take care of that
- [x] No, do it for me, I can't use GitHub...

**Comment by LuKePicci** [comment]
Done in 24a3ac3 Thanks. A preview of these changes is available in the latest branch of the website: https://hack-technicolor.readthedocs.io/en/latest/Repository/
