### ISSUE TITLE
Add 18.1.c.0514-950-RB for  DJA0230

### ISSUE THREAD

**Issue by TheLordOfTraps** [hack-technicolor/hack-technicolor#116]
**Important:** Please, check firmware isn't already listed in [Latest branch](https://hack-technicolor.readthedocs.io/en/latest/Repository) before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

18.1.c.0514-950-RB

## Device Info

Board Mnemonic:  VBNT-V

Model Number:  DJA0230

Vendor Name/Code:  Tesltra

## Where did you find it?

ISP RBI file link (if known):

- Protocol: 
- Link: 
- Restrictions (if any): 

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: 

## Did you manage to root this firmware version already?

- [ ] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [ x] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [ ] Yes! I will take care of that
- [ x] No, do it for me, I can't use GitHub...

Notes:
Sorry if this is annoying, the firmware is in the repo, but it isn't on there for my model so I didn't know if I would be able to flash or not.

**Comment by LuKePicci** [comment]
I'm a bit confused. Are you sharing a new firmware for DJA0230 or not? I see neither fw links nor attachments.

 I think we have the same fw version for DJA0231 already. Is it available for DJA0231 as well?

**Comment by TheLordOfTraps** [comment]
Sorry I'll try and explain what I meant.
My modem (DJA0230TLS) has FW (18.1.c.0514-950-RB) and I was wondering how do I gain Root so that I may share the FW as it isn't in the repo. I Couldn't find any instructions as to how this process is done.

**Comment by LuKePicci** [comment]
Ok, I suggest you try finding the new fw RBI download link by looking at other known ones. Maybe asking for help on whirlpool thread they can find the link for us. 

You can probably root it with the same strategy #C as its past versions. Let us know if it still works.
