### ISSUE TITLE
DGA4131FWB VBNT-O

### ISSUE THREAD

**Issue by miky2k** [hack-technicolor/hack-technicolor#117]
## Firmware version

18.3.n.0462_FW_261_DGA4131

## Device Info

Board Mnemonic: VBNT-O

Model Number: DGA4131FWB

Vendor Name/Code: Fastweb/Tecnicolor

ISP RBI file link (if known):

- Protocol: HTTP
- Link: http://59.0.121.191:8080/ACS-server/file/18.3.n.0462_FW_261_DGA4131.rbi
- Restrictions (if any): ISP Network only

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: 

## Did you manage to root this firmware version already?

- [ ] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [X] No, I can't root it following instructions from the wiki
- [ ] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [ ] Yes! I will take care of that
- [X] No, do it for me, I can't use GitHub...

**Comment by LuKePicci** [comment]
Please, follow firmware unpacking instruction from the wiki (Resources page) and show me /etc/config/cwmpd file contents

**Comment by miky2k** [comment]
Sorry but there is something wrong in 
https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/issues/20

and not work in my linux mint 20 i send you with wetransfer if you give me your mail.

**Comment by miky2k** [comment]
Sorry but there is something wrong in 
https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/issues/20

and not work in my linux mint 20 i send you with wetransfer if you give me your mail.

**Comment by miky2k** [comment]
Sorry but there is something wrong in 
https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/issues/20

and not work in my linux mint 20 i send you with wetransfer if you give me your mail.

**Comment by miky2k** [comment]
Sorry but there is something wrong in 
https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/issues/20

and not work in my linux mint 20 i send you with wetransfer if you give me your mail.

**Comment by LuKePicci** [comment]
I confirm the eth wan over vlan 835 is still there and available for use with strategy #9 

Closed by https://github.com/hack-technicolor/hack-technicolor/commit/a660b06ce51b255c31a38c282fffe193fa729164
