### ISSUE TITLE
WiFi over WiFi issue (not related to technicolor)

### ISSUE THREAD

**Issue by fa1rid** [hack-technicolor/hack-technicolor#119]
Hi Guys,

Sorry for posting an unrelated question here but I'm really annoyed from this issue and I need your opinion about it.

So, I have tested several times the following scenario (with different hardware) and I'm sure there's some kind of issue which I don't understand.

1st WiFi AP > WiFi Client > NAT > 2nd WiFi AP > Final WiFi Client (throughput is less than 1Mbps)

If both first and second AP uses 2.4GHz, then the speed becomes very low ~1Mbps, however if you replace second AP with 5GHz and keep the first one 2.4GHz, then there's no problem at all. What's going on? Anyone has any clue why this is happening please?

Thanks

**Comment by fa1rid** [comment]
I tested locally from end to end with iperf3 and same thing it's slow. "WiFi Client" speed is normal and no issue as I already say even with NAT using Ethernet to or 5GHz there's no problem.

Can this be a data fragmentation issue?

**Comment by hiatylellah** [comment]
Hi farid, I need to communicate with you, I am also living at  @fa1rid 
I need your support for Technicolor modem similar to yours
