### ISSUE TITLE
Add 18.1.c.0549-MR17-RB for DJA0230

### ISSUE THREAD

**Issue by gsstudios** [hack-technicolor/hack-technicolor#126]
**Important:** Please, check firmware isn't already listed in [Latest branch](https://hack-technicolor.readthedocs.io/en/latest/Repository) before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

18.1.c.0549-MR17-RB

## Device Info

Board Mnemonic: VBNT-V

Model Number: DJA0230

Vendor Name/Code: Telstra

## Where did you find it?

ISP RBI file link (if known):

- Protocol: HTTP
- Link: http://fwstore.bdms.telstra.net/Technicolor_vbnt-v_18.1.c.0549-MR17-RB/vbnt-v_18.1.c.0549-MR17-RB.rbi
- Restrictions (if any):

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: 

## Did you manage to root this firmware version already?

- [x] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [ ] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [x] Yes! I will take care of that
- [ ] No, do it for me, I can't use GitHub...

**Comment by LuKePicci** [comment]
Great, we'll wait for your PR. Thanks!

**Comment by gsstudios** [comment]
Thanks @LuKePicci. 
I've tested with Type 2 strategy and the DJA0230 has been very stable since.
