### ISSUE TITLE
OOM issue unpacking DJA0231 RBIs from device

### ISSUE THREAD

**Issue by workingfromhom** [hack-technicolor/hack-technicolor#128]
I was trying to do firmware upgrade on rooted Technicolor DJA0231 and was doing below commend to unpack the RBI image.

cat "/tmp/new.rbi" | (bli_parser && echo "Please wait..." && (bli_unseal | dd bs=4 skip=1 seek=1 of="/tmp/new.bin"))

Need some help on how to move the RBI file into the USB drive and use it as a working folder.

**Comment by Selmaks** [comment]
Try cd /mnt/usb or do cd /mnt/ and press tab a few times then use the usb location for the commands.

example  cat "/mnt/usb/USB-A/new.rbi" | (bli_parser && echo "Please wait..." && (bli_unseal | dd bs=4 skip=1 seek=1 of="/mnt/usb/USB-A/new.bin"))

type pwd and press enter that will give you the current directory you are in.

Also use https://github.com/seud0nym/tch-gui-unhide

**Comment by LuKePicci** [comment]
I edited the above comment such that this can be linked from the wiki.

**Comment by workingfromhom** [comment]
> 
> 
> Try `ls /tmp/run/mountd/` command from SSH then use the usb location you get for the commands, example:
> 
> ```shell
> root@OpenWrt:~# ls /tmp/run/mountd
> sda1
> ```
> 
> The usb mount location for above example is is `sda1`, so use `/tmp/run/mountd/sda1/new.bin` in place of `/tmp/new.bin` in all subsequent commands, for instance:
> 
> ```shell
> cat "/tmp/run/mountd/sda1/new.rbi" | (bli_parser && echo "Please wait..." && (bli_unseal | dd bs=4 skip=1 seek=1 of="/tmp/run/mountd/sda1/new.bin"))
> ```

Thanks This has worked fine
