### ISSUE TITLE
How to setup switch VLANs on these devices?

### ISSUE THREAD

**Issue by frehall** [hack-technicolor/hack-technicolor#130]
###
**EDIT:** My sollution is in [THIS](https://github.com/hack-technicolor/hack-technicolor/issues/130#issuecomment-723646232) post.
###

Im having a few of these devices laying around and was thinking to reuse them. For that I want VLANs configured but /etc/config/network looks very different compared to my other OpenWRT devices.

I would like my router to recieve VLAN1 and VLAN107 on port eth0. Then devices connected to port eth1 and eth2 should get ip from upstream DHCP on VLAN107 while port eth3 should get VLAN1-ip from upsream DHCP. Is this even possible? 

Also I have no use for the wan-port and was thinking I could better of using it as a local maintainance port.

Below is my complete /etc/config/network and its so much stuff in there I dont dare to do any changes risking to mess up something making it unreachable.

```
root@OpenWrt:~# cat /etc/config/network

config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option default_ps '0'

config interface 'lan'
        option ifname 'eth0 eth1 eth2 eth3'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.1.1'
        option netmask '255.255.255.0'
        option ip6assign '64'
        option force_link '0'
        option ipv6 '0'
        option ip6hint '0'
        option igmp_snooping '0'
        list pppoerelay ''
        list pppoerelay ''

config interface 'Guest1'
        option proto 'static'
        option ip6assign '64'
        option ipv6 '0'
        option ip6hint '1'
        option netmask '255.255.255.0'
        option ipaddr '192.168.168.1'
        option ifname 'wl0_1'
        option force_link '0'

config device 'phy_eth3'
        option name 'eth3'
        option mtu '1500'

config interface 'hotspot'
        option type 'bridge'
        option ifname 'gre-hotspot'

config switch 'bcmsw'
        option reset '1'
        option enable_vlan '0'
        option qosimppauseenable '0'

config interface 'wan'
        option auto '0'
        option proto 'dhcp'
        option reqopts '1 3 6 15 33 42 51 121 249'
        option iface6rd '6rd'
        option mtu6rd '1480'
        option vendorid 'LongLeaseTime'
        option ip4table 'main'
        option hostname 'TG799vn v2-CP1317CSAS2-16.2.7732-2221004'

config interface 'wwan'
        option auto '1'
        option metric '10'
        option proto 'mobiled'
        option session_id '0'
        option profile '1'

config interface 'iptv'
        option auto '0'
        option proto 'dhcp'
        option reqopts '1 3 6 15 33 42 51 121 249'
        option iface6rd '0'
        option vendorid 'IPTV_RGW_PRIV'
        option ip4table 'iptv'
        option dnsset 'iptv'

config interface 'voip'
        option auto '0'
        option proto 'dhcp'
        option ip4table 'voip'
        option reqopts '1 3 6 15 33 42 51 121 249'
        option iface6rd '0'
        option vendorid 'tel-002-'
        option dnsset 'voip'

config interface 'mgmt'
        option auto '0'
        option proto 'dhcp'
        option initboot '1'
        option ip4table 'mgmt'
        option reqopts '1 3 6 15 33 42 43 51 121 249'
        option iface6rd '0'
        option dnsset 'mgmt'

config interface 'gre'
        option peeraddr '213.64.234.83'
        option mtu '1578'
        option df '1'
        option zone 'wan'
        option tunlink 'wan'
        option ttl '100'
        option proto 'gretap'
        option network 'hotspot'

config device 'phy_eth4'
        option name 'eth4'
        option mtu '2000'

config device 'phy_ptm0'
        option name 'ptm0'
        option mtu '2000'

config device 'vlan_data'
        option ifname 'eth4'
        option name 'phy_eth4'

config device 'phy_atm'
        option name 'atm_wan'
        option mtu '2000'

config device 'vlan_iptv'
        option type '8021q'
        option ifname 'eth4'
        option name 'vlan_iptv'
        option vid '845'
        option macaddr 'A6:B1:E9:DB:9C:5D'
        option mtu '1500'

config device 'vlan_voip'
        option type '8021q'
        option ifname 'eth4'
        option name 'vlan_voip'
        option vid '855'
        option macaddr 'A4:B1:E9:DB:9C:5D'
        option mtu '1500'

config device 'vlan_mgmt'
        option type '8021q'
        option ifname 'eth4'
        option name 'vlan_mgmt'
        option vid '294'
        option macaddr 'A6:B1:E9:DB:9C:5C'
        option mtu '1500'

config config 'config'
        option wan_mode 'dhcp'

config interface 'ipoe'
        option proto 'dhcp'
        option metric '1'
        option reqopts '1 3 6 43 51 58 59'
        option release '1'
        option neighreachabletime '1200000'
        option neighgcstaletime '2400'
        option ipv6 '1'

config device 'waneth4'
        option enabled '1'
        option type '8021q'
        option name 'waneth4'
        option vid '835'

config device 'wanptm0'
        option enabled '1'
        option type '8021q'
        option name 'wanptm0'
        option vid '835'
```

**Comment by LuKePicci** [comment]
Do I understand correctly that none of devices connected to any switch port are required to reach the main SoC?

Is it just port 0 to port 1 & 2 (vlan 107) and port 0 to port 3 (vlan 1) what you need?

Then I confirm it's almost the same as in your other openwrt routers, but here your network file is still missing the switch vlan configuration you probably see elsewhere.
So define the external switch config stanza, set its enable vlan to 1 then define two switch_vlan stanzas, one set for vid 1 and the other for vid 107. Tag them as you wish, you can't keep two untagged vlans on the same port, so any of the two vlans must be tagged on port 0 at least. Whether you''d tag the others depends on your case. 
The switch_vlan on vid 107 will have ports 0, 1 & 2 assigned, the one on vid 1 will have ports 0 & 3 assigned. You can safely exclude port 8 (the main SoC, ie. eth0-3 interfaces) from both of them. Remove all eth0 to eth3 devices from the lan bridge interface. 

Yes you can recycle eth4 into a management port by simply adding eth4 into the lan bridge interface.

Please note the Wi-Fi interfaces will still be added into the lan bridge interface, so you won't get locked out via Wi-Fi.

**Comment by frehall** [comment]
> Do I understand correctly that none of devices connected to any switch port are required to reach the main SoC?
> 
If you by that mean that no devices needs to be able to reach the openwrt box, i.e. ssh/web it is correct. That box just works as a splitter because i have only one tp-cable coming to upper floor. But i would preffere if i somehow could connect to it to be able to admin it. And then the wan-port would be perfect for that.

Ive been reading different pages about how to setup vlan the entire day and every place say something different so im almost having an meltdown here haha. And cant quite follow your explanation. 
Just added eth4 to the lan bridge and now i cant reach the box anymore, again. It still forwards my traffic though as im able to write this. =)
Dont know how many reset and reroots i have had to do today.

**Comment by frehall** [comment]
Ehh,, wasnt ment to close it

**Comment by LuKePicci** [comment]
> If you by that mean that no devices needs to be able to reach the openwrt box, i.e. ssh/web it is correct.

awesome

> Just added eth4 to the lan bridge and now i cant reach the box anymore, again

eth4 needs some special care as it is normally involved in wan settings and wansensing service is taking care of it, so:
- disable & stop wansensing: `/etc/init.d/wansensing disable && /etc/init.d/wansensing stop`
- delete these two alien stanzas:
```
config device 'phy_eth4'
        option name 'eth4'
        option mtu '2000'

config device 'vlan_data'
        option ifname 'eth4'
        option name 'phy_eth4'
```
- reload network: `/etc/init.d/network reload`

Btw that is somehow unrelated to your main goal, and you can opt for wifi in place of eth4 if you'd like.

**Comment by frehall** [comment]
Thank you very much!

> Btw that is somehow unrelated to your main goal, and you can opt for wifi in place of eth4 for management if you'd like.

Every changes ive done to /etc/config/network has made the box unreachable even over Wifi. Sometimes ive still been able to connect through it but never to it. So a maintanance port would be awesome. Ill have a try right away!

**Comment by frehall** [comment]
So I have vlan1 and vlan107 tagged on the outgoing port of the upstream router which is the main router of the network with dhcp etc. Then i tag the incoming port of the router who has my workstation and a IoT connected. Then i untag vlan1 on the port for my ws and untag vlan107 on the port for the IoT. I guess im misunderstanding this completely because it does not work.

"option ports '0t 2'" in config switch_vlan is the same as eth0 and eth2, right? or how do i know port is what number?

**Comment by LuKePicci** [comment]
> So I have vlan1 and vlan107 tagged on the outgoing port of the upstream router which is the main router of the network with dhcp etc. Then i tag the incoming port of the router who has my workstation and a IoT connected. Then i untag vlan1 on the port for my ws and untag vlan107 on the port for the IoT

All correct.

> "option ports '0t 2'" in config switch_vlan is the same as eth0 and eth2, right?

All external switch ports 0 to 3 go to SoC via switch port 8. Because of DSA switch model you get traffic coming from port 0 (to 3) presented at interface eth0 (to 3).

switch_vlan for vid 107 should have option ports set to '0t 1* 2*', switch_vlan for vid 1 should have option ports set to '0t 3*'

**Comment by frehall** [comment]
Thank you very much for all the help you offering. Sadly I have to say suggested settings did not work.

root@OpenWrt:~# cat /etc/config/network
config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option default_ps '0'

config interface 'lan'
        option ifname ''
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.1.12'
        option netmask '255.255.255.0'
        option force_link '0'
        option ipv6 '0'
        option ip6hint '0'
        option igmp_snooping '0'
        list pppoerelay ''
        list pppoerelay ''
        option ip6assign '64'

config interface 'lan2'
        option ifname 'eth4'
        option type 'bridge'
        option proto 'static'
        option ipaddr '192.168.2.12'
        option netmask '255.255.255.0'

config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option vid '1'
        option ports '0t 3*'


config switch_vlan
        option device 'switch0'
        option vlan '2'
        option vid '107'
        option ports '0t 1* 2*'


config device 'phy_eth3'
        option name 'eth3'
        option mtu '1500'

config switch 'bcmsw'
        option reset '1'
        option enable_vlan '0'
        option qosimppauseenable '0'

config device 'phy_ptm0'
        option name 'ptm0'
        option mtu '2000'

config config 'config'

**Comment by LuKePicci** [comment]
You are setting up the wrong switch. The external switch you need to configure is the external one on unit 1. Also, proper bcmsw type needs to be set otherwise it won't use the correct driver.

**Comment by frehall** [comment]
> You are setting up the wrong switch. The external switch you need to configure is the external one on unit 1. Also, proper bcmsw type needs to be set otherwise it won't use the correct driver.

I guess I miss alot of fundamental knowledge to make this happen because I don't have a clue what you talking about or what I should change when you saying "external one on unit one". :( 

Also, do I need the bcmsw section at all? Thought it was some unused crap from the ISP setup.

**Comment by LuKePicci** [comment]
The bcmsw section you have already is the switch config of the internal switch on unit 0 (option unit is 0 by default).

Just clone that section, give it a different name, keep type as bcmsw, unit 1, enable vlan 1 and assign the two switch vlan to this switch. I'm sharing a full example in the next message.

**Comment by LuKePicci** [comment]
```uci
config switch 'bcmsw'
        option reset '1'
        option enable_vlan '0'
        option qosimppauseenable '0'
        option jumbo '0'

config switch 'bcmsw_ext'
        option reset '1'
        option type 'bcmsw'
        option qosimppauseenable '0'
        option unit '1'
        option enable_vlan '1'
        option jumbo '0'

config switch_vlan 'upstream1_switch'
        option device 'bcmsw_ext'
        option vlan '1'
        option ports '0t 3*'

config switch_vlan 'upstream107_switch'
        option device 'bcmsw_ext'
        option vlan '107'
        option ports '0t 1* 2*'
```

**Comment by frehall** [comment]
Sadly I have to report that this config setup did not work. Also, I think I've read somewhere that * are for tagging primary vlans and so untagged ports should just be the digit. Could that be?

**Comment by LuKePicci** [comment]
Correct * makes that port work on that vlan by default, ie you don't need to apply tagging from device. If you 'd like to apply tagging then change * to t

You don't need to apply tagging if that is the only vlan on such ports.

**Comment by frehall** [comment]
Talking about that, why is there no swconfig command and bcmswconfig does not support 'show' command.

**Comment by LuKePicci** [comment]
swconfig is based upon open switch configuration API which does not support DSA switch drivers.

roboconfig is based upon broadcom switch configuration API and does not support DSA switch drivers

bcmswconfig is a small utility from tch which translates UCI switch configuration stanzas into mdkshell commands

Run mdkshell then use vlan show to check current external switch vlan config

**Comment by frehall** [comment]
> swconfig is based upon open switch configuration API which does not support DSA switch drivers.
> 
> roboconfig is based upon broadcom switch configuration API and does not support DSA switch drivers
> 
> ethswctl is based upon broadcom switch configuration API and supports broadcom DSA switch drivers
> 
> bcmswconfig is a small utility from tch which translates UCI switch configuration stanzas into mdkshell commands
> 
> Run mdkshell then use vlan show to check current external switch vlan config

Okey, nice! mdkshell shows some interesting stuff!

##############
##############
As I dont manage to get it working on the device I've decided to have a try on my other Technicolor box:

#####
Product Vendor
Technicolor TG799VAc Xstream
Product Name
Telia WiFi-router Plus v3 
Software Version
17.2
Firmware Version
17.2.0339-1441018-20180416103837
Hardware Version
VBNT-H
#####

#####
root@OpenWrt:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='Chaos Calmer'
DISTRIB_REVISION='r46610'
DISTRIB_CODENAME='chaos_calmer'
DISTRIB_TARGET='brcm63xx-tch/VANTW'
DISTRIB_DESCRIPTION='OpenWrt Chaos Calmer 15.05.1'
DISTRIB_TAINTS='no-all busybox'
root@OpenWrt:~#
#####


To start with the default /etc/config/network is huge and i wonder how a default one with only standard LAN and WAN would look like? And from there adding the VLANs I've been so struggling to get going.

The orginilan network file is like this:


config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd35:d4fe:6793::/48'
	option default_ps '0'

config interface 'lan'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option gateway '192.168.1.2'
	option dns '8.8.8.8'
	option force_link '0'
	option ip6hint '0'
	option igmp_snooping '0'
	option ipv6 '0'
	option ip6assign '64'
	option ifname 'vlan_eth0 vlan_eth1 vlan_eth2 vlan_eth3 vlan_eth5'
	list pppoerelay ''

config interface 'Guest1'
	option proto 'static'
	option ip6assign '64'
	option ipv6 '0'
	option ip6hint '1'
	option netmask '255.255.255.128'
	option ipaddr '192.168.168.126'
	option ifname 'wl0_1'
	option force_link '0'

config interface 'Guest1_5GHz'
	option proto 'static'
	option ip6assign '64'
	option ipv6 '0'
	option ip6hint '2'
	option netmask '255.255.255.128'
	option ipaddr '192.168.168.254'
	option ifname 'wl1_1'
	option force_link '0'

config device 'vlan_eth0'
	option type '8021q'
	option ifname 'eth0'
	option name 'vlan_eth0'
	option vid '1'

config device 'vlan_eth1'
	option type '8021q'
	option ifname 'eth1'
	option name 'vlan_eth1'
	option vid '1'

config device 'vlan_eth2'
	option type '8021q'
	option ifname 'eth2'
	option name 'vlan_eth2'
	option vid '1'

config device 'vlan_eth3'
	option type '8021q'
	option ifname 'eth3'
	option name 'vlan_eth3'
	option vid '1'

config device 'phy_eth3'
	option name 'eth3'
	option mtu '1500'

config switch 'bcmsw_int'
	option reset '1'
	option type 'bcmsw'
	option qosimppauseenable '0'
	option unit '0'
	option enable_vlan '0'

config switch 'bcmsw_ext'
	option reset '1'
	option type 'bcmsw'
	option qosimppauseenable '0'
	option unit '1'
	option enable_vlan '1'

config switch_vlan
	option device 'bcmsw_ext'
	option vlan '1'
	option ports '0* 1* 2* 3* 8t 5*'

config smartcontrol 'smartcontrol'
	option switch_port '0*'

config interface 'hotspot'
	option type 'bridge'
	option ifname 'gre-hotspot'

config device 'vlan_eth5'
	option type '8021q'
	option ifname 'eth5'
	option name 'vlan_eth5'
	option vid '1'
	option multicast_router '2'

config interface 'wan'
	option auto '0'
	option proto 'dhcp'
	option reqopts '1 3 6 15 33 42 51 121 125 249'
	option release '1'
	option iface6rd '6rd'
	option mtu6rd '1480'
	option vendorid 'LongLeaseTime'
	option ip4table 'main'
	option hostname 'Telia WiFi-router Plus v3-CP1752TASDZ-17.2.0339-1441018'
	option dns_metric '0'

config interface 'wan6'
	option ifname '@wan'
	option proto 'dhcpv6'
	option reqopts '23 25'
	option noslaaconly '1'
	option dns_metric '1'
	option auto '0'

config interface 'wwan'
	option auto '1'
	option metric '10'
	option proto 'mobiled'
	option session_id '0'
	option profile '1'

config interface 'iptv'
	option auto '0'
	option proto 'dhcp'
	option reqopts '1 3 6 15 33 42 51 121 249'
	option release '1'
	option iface6rd '0'
	option vendorid 'IPTV_RGW_PRIV'
	option ip4table 'iptv'
	option dnsset 'iptv'

config interface 'voip'
	option auto '0'
	option proto 'dhcp'
	option ip4table 'voip'
	option reqopts '1 3 6 15 33 42 51 121 249'
	option release '1'
	option iface6rd '0'
	option vendorid 'tel-002-'
	option dnsset 'voip'

config interface 'mgmt'
	option auto '0'
	option proto 'dhcp'
	option initboot '1'
	option ip4table 'mgmt'
	option reqopts '1 3 6 15 33 42 43 51 121 249'
	option release '1'
	option iface6rd '0'
	option dnsset 'mgmt'

config interface 'gre'
	option peeraddr '213.64.234.83'
	option mtu '1578'
	option df '1'
	option zone 'wan'
	option tunlink 'wan'
	option ttl '100'
	option proto 'gretap'
	option network 'hotspot'

config device 'phy_eth4'
	option name 'eth4'
	option mtu '1500'

config device 'phy_ptm0'
	option name 'ptm0'
	option mtu '1500'

config device 'vlan_data'
	option ifname 'eth4'
	option name 'phy_eth4'

config device 'phy_atm'
	option name 'atm_wan'
	option mtu '1500'

config device 'vlan_iptv'
	option type '8021q'
	option ifname 'eth4'
	option name 'vlan_iptv'
	option vid '845'
	option macaddr 'A6:91:B1:36:14:7B'
	option mtu '1500'

config device 'vlan_voip'
	option type '8021q'
	option ifname 'eth4'
	option name 'vlan_voip'
	option vid '855'
	option macaddr 'A4:91:B1:36:14:7B'
	option mtu '1500'

config device 'vlan_mgmt'
	option type '8021q'
	option ifname 'eth4'
	option name 'vlan_mgmt'
	option vid '294'
	option macaddr 'A6:91:B1:36:14:7A'
	option mtu '1500'

config config 'config'

**Comment by LuKePicci** [comment]
Here you see the four external switch ports are all set to untagged with * and as part of virtual switch on id 1. Then the SoC port 8 is set to tagged with t. That's why you see four 8021q devices defined on top of eth0-3 as vlan_eth0 and so on. Additionally, here you have a dedicate additional wireless SoC for the 5GHz radio connected as an ethernet device on external switch port 5, untagged as well such that

I would suggest you avoid re-using vlan 1 here as its already taken by the default lan config. That, said the usual config will work the same as before:
``
config switch 'bcmsw_int'
        option reset '1'
        option type 'bcmsw'
        option enable_vlan '0'
        option qosimppauseenable '0'
        option unit '0'
        option jumbo '0'

config switch 'bcmsw_ext'
        option reset '1'
        option type 'bcmsw'
        option qosimppauseenable '0'
        option unit '1'
        option enable_vlan '1'
        option jumbo '0'

config switch_vlan 'lan_switch'
	option device 'bcmsw_ext'
	option vlan '1'
	option ports '8t 5*'      # <- ports 0 to 3 removed

config switch_vlan 'upstream1_switch'
        option device 'bcmsw_ext'
        option vlan '17'                              # <- not using vid 1 as it's taken by default lan
        option ports '0t 3*'

config switch_vlan 'upstream107_switch'
        option device 'bcmsw_ext'
        option vlan '107'
        option ports '0t 1* 2*'
```

**Comment by frehall** [comment]
> Then the SoC port 8 is set to tagged with t. That's why you see four 8021q devices defined on top of eth0-3 as vlan_eth0 and so on. 
Ahh. thanks for the information. I really learn alot new stuff along the road here! : D

> 
> I would suggest you avoid re-using vlan 1 here as its already taken by the default lan config.
So like this is not an option?:
 
 ```
 config switch 'bcmsw_int'
         option reset '1'
         option type 'bcmsw'
         option enable_vlan '0'
         option qosimppauseenable '0'
         option unit '0'
         option jumbo '0'
 
 config switch 'bcmsw_ext'
         option reset '1'
         option type 'bcmsw'
         option qosimppauseenable '0'
         option unit '1'
         option enable_vlan '1'
         option jumbo '0'
 
 config switch_vlan 'lan_switch'
 	option device 'bcmsw_ext'
 	option vlan '1'
 	option ports '8t 0* 3* 5*'          # <- ports 0 and 3 readded
 
 config switch_vlan 'upstream107_switch'
         option device 'bcmsw_ext'
         option vlan '107'
         option ports '0t 1* 2*'
 ```

I mean, if there already is a default LAN at vid 1, I could just keep using that?

**Comment by LuKePicci** [comment]
You could but this will break in undefined ways the 5GHz wi-fi radio. That 5GHz radio on discrete SoC connected to port 5 gets configured after boot via switch link on vlan 1 between port 8t and port 5*. Removing this link makes the 5GHz wireless chip isolated from its configuration services. You will probably see a wireless network with SSID "Quantenna" which will be part of your vid 1 switch becasue of 5* is still in there.

**Comment by frehall** [comment]
Oh, that sounds complicated! But hmm, in my example there is nothing done to 8t and 5 in vid 1. Only 1 and 2 moved to vid 107.

My next task is to add wifi to the networks but I'll go for 2.4ghz and actually have no need for 5ghz at all.

**Comment by LuKePicci** [comment]
> But hmm, in my example there is nothing done to 8t and 5 in vid 1. Only 1 and 2 moved to vid 107.

You're right, then vlan 1 members will reach the lan interface bridge and will be allowed to "manage" the main OS, unless some extra restriction is done within OS and outside of the switch scope.

**Comment by LuKePicci** [comment]
> My next task is to add wifi to the networks but I'll go for 2.4ghz

You can't do this at switch level. The main 2.4 wireless radio is not connected to the external switch. You would need to create a second lan bridge interface and a second group of 8021q devices to put in there along with the 2.4 wireless radio.

**Comment by LuKePicci** [comment]
The creation of a separate lan interface and its binding to some custom switch vlan is covered already at https://github.com/Ansuel/tch-nginx-gui/issues/853

I would prefer to keep this topic clean as reference for other users and focused on the switch thing only if you agree.

**Comment by frehall** [comment]
> I would prefer to keep this topic clean as reference for other users and focused on the switch thing only if you agree.

I totaly agree!

I have already posted my default /etc/config/network file in here and will add my current working one at the end of this post. But first I want to hilight what I have done to make this work.


```config switch 'bcmsw_ext'
	option reset '1'
	option type 'bcmsw'
	option qosimppauseenable '0'
	option unit '1'
	option enable_vlan '1'```
Nothing changed here.. adding `option jumbo '0'` was adviced but as I dont know what it does and it seems to work anyway I did not add it.

```config switch_vlan
	option device 'bcmsw_ext'
	option vlan '1'
	option ports '0* 3* 8t 5*'```
In this section I just removed the ports I wanted to isolate on another VLAN. (Port 1 and 2)

```config switch_vlan 'upstream107_switch'
        option device 'bcmsw_ext'
        option vlan '107'
        option ports '0t 1* 2*'```
This section is completely new and this is where LAN-port 1 and 2 is added to VLAN 107. (On my router these ports are numbered 2 and 3)

So what I got in the end was port 0 (numbered 1 on the box) connected to upstream router recieving VLAN1 untagged and VLAN107 tagged.
Port 1 and 2 members of VLAN107 for some IoT-stuff. 
Port 3 isnt really changed so its still member of default VLAN1 and thats where I have my workstation connected.

Finaly I'll post /etc/config/network as it is now. I have been trying to clean it up as much as i dare from ISP-specific stuff but might still be some useless stuff in it: (For instance, what is "phy_ptm0" and "phy_atm"
```
config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd35:d4fe:6793::/48'
	option default_ps '0'

config interface 'lan'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option gateway '192.168.1.2'
	option dns '8.8.8.8'
	option force_link '0'
	option ip6hint '0'
	option igmp_snooping '0'
	option ipv6 '0'
	option ip6assign '64'
	option ifname 'vlan_eth0 vlan_eth3 vlan_eth5'
	list pppoerelay ''

config device 'vlan_eth0'
	option type '8021q'
	option ifname 'eth0'
	option name 'vlan_eth0'
	option vid '1'

config device 'vlan_eth1'
	option type '8021q'
	option ifname 'eth1'
	option name 'vlan_eth1'
	option vid '1'

config device 'vlan_eth2'
	option type '8021q'
	option ifname 'eth2'
	option name 'vlan_eth2'
	option vid '1'

config device 'vlan_eth3'
	option type '8021q'
	option ifname 'eth3'
	option name 'vlan_eth3'
	option vid '1'

config device 'phy_eth3'
	option name 'eth3'
	option mtu '1500'

config switch 'bcmsw_int'
	option reset '1'
	option type 'bcmsw'
	option qosimppauseenable '0'
	option unit '0'
	option enable_vlan '0'

config switch 'bcmsw_ext'
	option reset '1'
	option type 'bcmsw'
	option qosimppauseenable '0'
	option unit '1'
	option enable_vlan '1'

config switch_vlan
	option device 'bcmsw_ext'
	option vlan '1'
	option ports '0* 3* 8t 5*'

config switch_vlan 'upstream107_switch'
        option device 'bcmsw_ext'
        option vlan '107'
        option ports '0t 1* 2*'

config smartcontrol 'smartcontrol'
	option switch_port '0*'

config interface 'hotspot'
	option type 'bridge'
	option ifname 'gre-hotspot'

config device 'vlan_eth5'
	option type '8021q'
	option ifname 'eth5'
	option name 'vlan_eth5'
	option vid '1'
	option multicast_router '2'

config interface 'wan'
	option auto '0'
	option proto 'dhcp'
	option reqopts '1 3 6 15 33 42 51 121 125 249'
	option release '1'
	option iface6rd '6rd'
	option mtu6rd '1480'
	option vendorid 'LongLeaseTime'
	option ip4table 'main'
	option hostname 'Telia WiFi-router Plus v3-CP1752TASDZ-17.2.0339-1441018'
	option dns_metric '0'

config interface 'wan6'
	option ifname '@wan'
	option proto 'dhcpv6'
	option reqopts '23 25'
	option noslaaconly '1'
	option dns_metric '1'
	option auto '0'

config interface 'wwan'
	option auto '1'
	option metric '10'
	option proto 'mobiled'
	option session_id '0'
	option profile '1'


config device 'phy_eth4'
	option name 'eth4'
	option mtu '1500'

config device 'phy_ptm0'
	option name 'ptm0'
	option mtu '1500'

config device 'vlan_data'
	option ifname 'eth4'
	option name 'phy_eth4'

config device 'phy_atm'
	option name 'atm_wan'
	option mtu '1500'

config config 'config'```

**Comment by LuKePicci** [comment]
I cleaned it up a little more. atm and ptm refer to the DSL modem interface. Those other phy_* stuff looks like garbage to me, I'm quite skeptical they would even had any effect. I removed vlan_eth1 and vlan_eth2 devices since you are not longer presenting those interfaces to the SoC.

**Comment by frehall** [comment]
I am running low on switches on my network so I decided to have a new go on the Technicolor I wasnt able to get VLAN configured on in the first place. As a starting point I have set it up so switch port 0 is trunk port connected to main router for VLAN 1 and 107 and rest of the LAN-port 1-3 are for VLAN1. I cant see anything wrong in my config but still it does not work so it has to be something wrong I'm not aware of. Thats why Im asking for help yet again. 

/etc/config/network looks like:
```

config interface 'loopback'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option default_ps '0'

config interface 'lan'
	option ifname 'vlan_eth0 vlan_eth1 vlan_eth2 vlan_eth3'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.12'
	option netmask '255.255.255.0'
	option gateway '192.168.1.2'
	option dns '192.168.1.2'
	option ip6assign '64'
	option force_link '0'
	option ipv6 '0'
	option ip6hint '0'
	option igmp_snooping '0'
	list pppoerelay ''
	list pppoerelay ''

config interface 'lan2'
	option ifname 'eth4'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.2.12'
	option netmask '255.255.255.0'
	option gateway '192.168.1.2'
	option dns '192.168.1.2'

config device 'vlan_eth0'
        option type '8021q'
        option ifname 'eth0'
        option name 'vlan_eth0'
        option vid '1'

config device 'vlan_eth1'
        option type '8021q'
        option ifname 'eth1'
        option name 'vlan_eth1'
        option vid '1'

config device 'vlan_eth2'
        option type '8021q'
        option ifname 'eth2'
        option name 'vlan_eth2'
        option vid '1'

config device 'vlan_eth3'
        option type '8021q'
        option ifname 'eth3'
        option name 'vlan_eth3'
        option vid '1'
                                

#config device 'phy_eth3'
#	option name 'eth3'
#	option mtu '1500'


config switch 'bcmsw'
	option reset '1'
	option enable_vlan '0'
	option qosimppauseenable '0'

config switch 'bcmsw_ext'
        option reset '1'
        option type 'bcmsw'
        option qosimppauseenable '0'
        option unit '0'
        option enable_vlan '1'
#        option jumbo '0'


config switch_vlan
        option device 'bcmsw_ext'
        option vlan '1'
        option ports '0t 1* 2* 3* 8t' 
                        





config config 'config'
	option wan_mode 'dhcp'
```

**Comment by LuKePicci** [comment]
bcmsw_ext should be unit 1

**Comment by frehall** [comment]
> bcmsw_ext should be unit 1

I changed to unit 0 because using 1 showed this:

```
root@OpenWrt:~# /etc/init.d/network restart
Success
JUMBO_PORT_MASK:0x00000000
  GPHY_0 port rejects jumbo frames.
  GPHY_1 port rejects jumbo frames.
  GMII_1 port rejects jumbo frames.
  GMII_2 port rejects jumbo frames.
  GPON_SERDES port rejects jumbo frames.
  MOCA port rejects jumbo frames.
  USB port rejects jumbo frames.
  GPON port rejects jumbo frames.
  MIPS port rejects jumbo frames.
Success
Success
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
*** error: Unit 1 is not valid
root@OpenWrt:~#
```

**Comment by LuKePicci** [comment]
What's the output from: `ethswctl -c switchinfo -v 1` ?

Did you try this?
```
config switch 'bcmsw_int'
        option reset '1'
        option type 'bcmsw'
        option enable_vlan '0'
        option qosimppauseenable '0'
        option unit '0'
        option jumbo '0'

config switch 'bcmsw_ext'
        option reset '1'
        option type 'bcmsw'
        option qosimppauseenable '0'
        option unit '1'
        option enable_vlan '1'
        option jumbo '0'
```

**Comment by frehall** [comment]
> What's the output from: `ethswctl -c switchinfo -v 1` ?

root@OpenWrt:~# ethswctl -c switchinfo -v 1
Port Map = 0x0; Phy Port Map = 0x0
No switch connected
Success
root@OpenWrt:~# ethswctl -c switchinfo -v 0
Port Map = 0xf8; Phy Port Map = 0xf8
Switch connected through UBUS
VendorID = 0x6300, Dev ID = 0x63268, Rev ID = 0x0, epon_port=-1, Success
root@OpenWrt:~#

> 
> Did you try this?
> 
> ```
> config switch 'bcmsw_int'
>         option reset '1'
>         option type 'bcmsw'
>         option enable_vlan '0'
>         option qosimppauseenable '0'
>         option unit '0'
>         option jumbo '0'
> 
> config switch 'bcmsw_ext'
>         option reset '1'
>         option type 'bcmsw'
>         option qosimppauseenable '0'
>         option unit '1'
>         option enable_vlan '1'
>         option jumbo '0'
> ```

Whenever I use unit 1 i get same error:
`*** error: Unit 1 is not valid`

**Comment by frehall** [comment]
Funny thing is. The router is able to reach internet but my workstation connected to port 3 doesnt even get an IP from network DHCP.

**Comment by LuKePicci** [comment]
Which board is this?

**Comment by frehall** [comment]
TG799TSvn v2
Product: vdnt-o_telia_r16-2
Release: Jade (16.2)
Version: 16.2.7732-2221004-20170502175300-dc9dfe4b113edc29fd43209a51f43c09c374d83a

**Comment by LuKePicci** [comment]
I have a vdnt-o too (not from telia) but I don't even know if it has the external switch. It's clearly not the same switch IC of your other tch. I can't really help you here. What we were discussing at the beginning of this thread is relevant for other 63268 boards like vant-6 and newer 63138 ones.

I can only suggest you to remove the entire bcmsw_ext stanza and try to configure the internal switch on unit 0 directly, something like this:;

```
config switch 'bcmsw'
        option reset '1'
        option type 'bcmsw'
        option enable_vlan '1'
        option qosimppauseenable '0'
        option unit '0'
        option jumbo '0'

config switch_vlan
        option device 'bcmsw_ext'
        option vlan '1'
        option ports '0t 1* 2* 3* 8t' 
```

**Comment by frehall** [comment]
That didnt do it eather..
Its gigabit but no 5ghz.
