### ISSUE TITLE
Improvements to safe upgrade process

### ISSUE THREAD

**Issue by katzieren** [hack-technicolor/hack-technicolor#152]
Hi. I've been poking around TG799vac (VBNT-H) I've bought recently and got two suggestions.

1. After safe upgrade from 16.2 to 17.2 dnsmasq is unable to start because it's getting removed from /etc/shadow and /etc/passwd. I suggest executing:
```
cp /rom/etc/passwd /etc/passwd
cp /rom/etc/shadow /etc/shadow
```
before reboot. Issue's been mentioned [here](https://dev.archive.openwrt.org/ticket/22300.html) as well.

2. Instead of telling people to power cycle their devices, we can add sysrq to cause kernel crash and reboot the device.
`echo c > /proc/sysrq-trigger`

Tested those solutions on my device, both work perfectly. I incorporated them into a script because I grew tired of typing commands while troubleshooting [issues I've had](https://github.com/hack-technicolor/hack-technicolor/discussions/151).

```
#!/bin/sh

mkdir -p /overlay/`cat /proc/banktable/booted`/etc
chmod 755 /overlay/`cat /proc/banktable/booted` /overlay/`cat /proc/banktable/booted`/etc
echo -e "echo root:root | chpasswd
sed -i 's#/root:.*\$#/root:/bin/ash#' /etc/passwd
sed -i -e 's/#//' -e 's#askconsole:.*\$#askconsole:/bin/ash#' /etc/inittab
uci -q set \$(uci show firewall | grep -m 1 \$(fw3 -q print | \
egrep 'iptables -t filter -A zone_lan_input -p tcp -m tcp --dport 22 -m comment --comment \"!fw3: .+\" -j DROP' | \
sed -n -e 's/^iptables.\+fw3: \(.\+\)\".\+/\1/p') | \
sed -n -e \"s/\(.\+\).name='.\+'$/\1/p\").target='ACCEPT'
uci add dropbear dropbear
uci rename dropbear.@dropbear[-1]=afg
uci set dropbear.afg.enable='1'
uci set dropbear.afg.Interface='lan'
uci set dropbear.afg.Port='22'
uci set dropbear.afg.IdleTimeout='600'
uci set dropbear.afg.PasswordAuth='on'
uci set dropbear.afg.RootPasswordAuth='on'
uci set dropbear.afg.RootLogin='1'
uci set dropbear.lan.enable='0'
uci commit dropbear
/etc/init.d/dropbear enable
/etc/init.d/dropbear restart
rm /overlay/\$(cat /proc/banktable/booted)/etc/rc.local
" > /overlay/`cat /proc/banktable/booted`/etc/rc.local
chmod +x /overlay/`cat /proc/banktable/booted`/etc/rc.local
mtd write "/mnt/usb/SanDisk_Ultra_2_33f6/172405h1441028closed.bin" bank_2
cp /rom/etc/passwd /etc/passwd
cp /rom/etc/shadow /etc/shadow
echo c > /proc/sysrq-trigger
```

3. Not sure if it's true for other devices, but VBNT-H (and likely VANT-W and VBNT-F since I see those board configs mentioned in `/etc/boards/`) require you to modify ssh config while connecting from linux host. Windows OpenSSH as well as macOS connect without any issues, but on my laptop running Fedora I had to modify /home/$USER/.ssh/config file to allow DH key exchange.
```
echo "Host 192.168.1.1
      KexAlgorithms +diffie-hellman-group1-sha1" > .ssh/config
```

**Comment by katzieren** [comment]
1. I stand corrected. There's not much of a reason to keep config from 16.2, unless you have broken hardware (like me, since I still have no idea why 17.2 doesn't boot with endpointdd loaded).

2. I wouldn't have suggested it otherwise, I believe that bootloader sees it as regular system reboot :)

https://user-images.githubusercontent.com/81479208/113311864-03f0c980-930a-11eb-8c32-ba196aa003eb.mp4

**Comment by LuKePicci** [comment]
Looks good, included in https://github.com/hack-technicolor/hack-technicolor/commit/bb29355eaecbefd218e677aace63eff97eb764d4 and https://github.com/hack-technicolor/hack-technicolor/commit/014903e9efd2b8a0ea3055ad42e66988338b7d5f
