### ISSUE TITLE
20.3.c.0329-MR19-RA for VBNT-V and VCNT-A causes sync issues

### ISSUE THREAD

**Issue by seud0nym** [hack-technicolor/hack-technicolor#180]
The firmware repository contains 20.3.c.0329-MR19-RA for both the VBNT-V (DJA0230) and VCNT-A (DJA0231) devices.

However, this firmware contains a broken adsl_phy.bin that can cause sync issues. There is a later release (20.3.c.0329-MR19-RB) for both devices:

DJA0230: http://fwstore.bdms.telstra.net/Technicolor_vbnt-v_20.3.c.0329-MR19-RB/vbnt-v_20.3.c.0329-MR19-RB.rbi
DJA0231: http://fwstore.bdms.telstra.net/Technicolor_vcnt-a_20.3.c.0329-MR19-RB/vcnt-a_20.3.c.0329-MR19-RB.rbi

I have confirmed the only difference between RA and RB releases is the version update and the new adsl_phy.bin:

```
Filename			Folder		Comparison result		Left Date		Right Date
adsl_phy.bin			etc\adsl	Binary files are different	28/05/2021 7:50:49 PM	* 19/07/2021 12:04:44 PM
version				etc\config	Text files are different	29/05/2021 1:38:24 AM	* 19/07/2021 4:18:28 PM	
versioncusto			etc\config	Text files are different	28/05/2021 7:50:52 PM	* 19/07/2021 12:04:44 PM	
banner				etc		Text files are different	29/05/2021 1:38:24 AM	* 19/07/2021 4:18:28 PM
```

The broken RA release should be replaced with the new RB release.

**Comment by seud0nym** [comment]
It appears those links no longer work. The files are available here:

https://www.dropbox.com/s/fijq1zmsssgdqhk/vbnt-v_20.3.c.0329-MR19-RB.rbi?dl=0
https://www.dropbox.com/s/v9jzpazxdyy99fd/vcnt-a_20.3.c.0329-MR19-RB.rbi?dl=0

**Comment by LuKePicci** [comment]
Original links work as expected, could you kindly add them into the repo page? Thanks

**Comment by seud0nym** [comment]
The links were down for about 10 hours yesterday, and I was concerned that they would not come back.

Do I have to fork the whole repository to edit the single file? 
How do the torrent links work?
Do I have to upload the rbi files as well?
