### ISSUE TITLE
Add AGTSA_1.0.0_001_CLOSED for VCNT-D

### ISSUE THREAD

**Issue by lorenzocanalelc** [hack-technicolor/hack-technicolor#191]
**Important:** Please, check firmware isn't already listed in [Latest branch](https://hack-technicolor.readthedocs.io/en/latest/Repository) before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

AGTSA_1.0.0_001_CLOSED

## Device Info

Board Mnemonic: VCNT-D (??)

Model Number: DGA2231 (??)

Vendor Name/Code: TIM

## Where did you find it?

ISP RBI file link (if known): 

- Protocol: https
- Link: https://fw.regman-tl.interbusiness.it:11443/Firmware/TR069/AGThomson/AGTSA_1.0.0_001_CLOSED.rbi
- Restrictions (if any): Link works on ISP network only

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: https://www.mediafire.com/file/cdmwh5udqmvnllr/AGTSA_1.0.0_001_CLOSED.rbi/file

## Did you manage to root this firmware version already?

- [ ] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [X] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [X] Yes! I will take care of that
- [ ] No, do it for me, I can't use GitHub...

So, I found this using the Tim Versioning file on uci-default, but I'm not sure about the board (I found it on the file I mentioned) or the model number (This is taken from the RBI itself). I have no idea about the Technicolor Homeware version put I leave it here since it could be helpful for someone with this board to get root to it (It is probably the same firmware as the AGTHF_1.0.0_001 or even older).

**Comment by lorenzocanalelc** [comment]
#203

**Comment by LuKePicci** [comment]
So this was a VCNT-C. Let me fix this issue title
