### ISSUE TITLE
Support for Technicolor TG799vac (VANT-W) from Telia in Sweden

### ISSUE THREAD

**Issue by Fallenub** [hack-technicolor/hack-technicolor#231]
**General info**

My gateway is currently running firmware version 16.2.7732-2221002-20170502175535 from Telia Sweden

**Did anybody ever manage to get root on that device already?**

*Select all applicable*

- [x ] Yes, by using a root strategy listed in the wiki

After rooting everything was fine, I had access to both 2.4 and 5Ghz AP.
I followed your post about getting DSL working on them through configuring PPPoE. This worked like a charm as well.
However, I lost access to the 5Ghz wifi, it does not appear in my webui (default). Is there anyway to solve this?

Thank you!

**Comment by LuKePicci** [comment]
This Support template is intended for new models which are not yet listed on the wiki.

If you need help on a general issue with wifi I prefer to convert this into a normal discussion (with no issue tracking).

Th problem you describe could be related to some network config you did on the local switch/network settings. The 5G wifi chip on this model is on a separate SoC internally connected as any other LAN ethernet device, that's why it could have been disconnected by wrong lan settings.

**Comment by Fallenub** [comment]
Sorry, I am new to github, I was not aware of this, should I delete this or mark it as resolved and ask somewhere else? 

I am not really sure what I did to cause this, I changed the following settings in the network:
config interface 'lan'
	option type 'bridge'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option force_link '0'
	option ip6hint '0'
	option igmp_snooping '0'
	option ipv6 '0'
	option ip6assign '64'
	option ifname 'vlan_eth0 vlan_eth1 vlan_eth2 vlan_eth3 vlan_eth5'
	list pppoerelay 'atm0 vlan_data'
	list ifname 'wanptm0'
	list pppoerelay ''

config interface 'wan'
	option auto '1'
	option proto 'pppoe'
	option username 'D25@-4com'
	option password 'xxx'
	option authfail '0'
	option iface6rd '6rd'
	option zone6rd 'wan'
	option initboot '1'
	option ipv6 '0'
	option mtu6rd '1480'
	option ifname 'ptm0'
	option vendorid 'LongLeaseTime'
	option ip4table 'main'
	option hostname 'Telia WiFi-router Plus-CP1701RA2F1-16.2.7732-2221002'
	list dns '1.1.1.1'
	list dns '1.0.0.1'
	option peerdns '1'

config device 'phy_atm'
	option name 'ptm0'
	option mtu '1480'

config device 'vlan_data'
	option ifname 'eth4'
	option name 'phy_eth4'

config device 'phy_atm'
	option name 'ptm0'
	option mtu '1480'

option wan_mode 'pppoe'

config device 'wanptm0'
	option enabled '1'
	option name 'wanptm0'
	option ipv6 '0'

config device 'if0atm'
	option enabled '1'
	option name 'ptm0'

config atmdevice 'atm_wan'
	option ulp 'eth'
	option vpi '0'
	option vci '35'
	option path 'fast'
	option enc 'llc'

I am thinking about what you said and does that mean i should add option ifname 'eth5' to vland_data?
