### ISSUE TITLE
Add 18.3.n.0482_FW_264 for DGA4131 (VBNT-O)

### ISSUE THREAD

**Issue by pcrunner** [hack-technicolor/hack-technicolor#244]
**Important:** Please, check firmware isn't already listed in [Latest branch](https://hack-technicolor.readthedocs.io/en/latest/Repository) before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

18.3.n.0482_FW_264_DGA4131

## Device Info

Board Mnemonic: VBNT-O for DGA4131FWB

Model Number: DGA4131FWB

Vendor Name/Code: FASTWEB for DGA4131FWB

## Where did you find it?

ISP RBI file link (if known):

- Protocol: 
- Link: 
- Restrictions (if any): 

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: 

## Did you manage to root this firmware version already?

- [ ] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [X] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [ ] Yes! I will take care of that
- [X ] No, do it for me, I can't use GitHub...

**Comment by LuKePicci** [comment]
Done in #252
