### ISSUE TITLE
Add 19.4.l.0393-MR1-RB for DWA0122 (VCNT-2) from Belong Australia

### ISSUE THREAD

**Issue by indikadaprogrammer** [hack-technicolor/hack-technicolor#247]
**Important:** Please, check firmware isn't already listed in [Latest branch](https://hack-technicolor.readthedocs.io/en/latest/Repository) before opening a new one. Use the "Model Support Request" issue template in place of this one in case you're going to share the first firmware for your gateway device.

Please fill out the following, remembering to put an 'x' in the '[ ]' to mark the checkbox:

## Firmware version

19.4.l.0393-MR1-RB

## Device Info

Board Mnemonic: VCNT-2

Model Number: DWA0122

Vendor Name/Code: Belong (Australia)

## Where did you find it?

ISP RBI file link (if known):

- Protocol: https
- Link: https://fw.ax.belong.com.au/vcnt-2_19.4.l.0393-MR1-RB.rbi
- Restrictions (if any): I am not with ISP so not sure how to get it. I could not access the above url from public internet (using another ISP).

Attach the RBI firmware in case above URL is restricted, or attach a bank dump if RBI URL is unknown:

- Firmware file: Could not get access to the firmware rbi.

## Did you manage to root this firmware version already?

- [ X] Yes, following Type 2 instructions
- [ ] Yes, following Type 1 instructions
- [ ] Yes, following Type 3 instructions
- [ ] No, I can't root it following instructions from the wiki
- [ ] I didn't try

## Would you take care of adding this new firmware in the wiki?

- [ X] Yes! I will take care of that
- [ ] No, do it for me, I can't use GitHub...

**Comment by LuKePicci** [comment]
Hi, sorry for the delayed reply. This looks promising, I'm fairly confident we could finally find the RBI's for this Belong's VCNT-2.

As I see from your bank_1 it was at version 19.4.0381-RA, which is the same version mentioned in #172 Your active bank should be bank_2 now and running the updated release from the RBI 19.4.l.0393-MR1-RB.

We already have a dump for the older bank_1 and your tests with this new one being rootable as Type 2 makes that RBI crucial to grab.

**Comment by LuKePicci** [comment]
We got the RBI, a nice guy shared it on the other issue, you can get it via Torrent.

**Comment by brainstorm** [comment]
> We got the RBI, a nice guy shared it on the other issue, you can get it via Torrent.

That torrent is not seeded anymore :_/
