### ISSUE TITLE
Support for Technicolor DGA0122NLK from SSE in the UK

### ISSUE THREAD

**Issue by BonesMgee** [hack-technicolor/hack-technicolor#261]
**General info**

My gateway is currently running firmware version 19.4.0477 from SSE in the UK

- Product: *DGA0122NLK*
- ISP: *SSE (pretty sure SSE resell a Vodafone connection)*
- Countries: *(United Kingdom)*
- Commercial name from the ISP: *Broadband DGA0122 Wi-Fi Router*
- Board: *VCNT-P*

**Did anybody ever manage to get root on that device already?**

*Select all applicable*

- [ ] Yes, by using a root strategy listed in the wiki
- [* ] Yes, following another different strategy
- [ ] No, as far as I know it has never been rooted

*Say something more about the adopted strategy here*
 Provided Strategy No Longer Works!
**Firmware versions**

*Please fill as many available info about each firmware versions you have ever heard about for this board. Leave unknown parts empty.*

- Version: *19.4.0477*
- Full version: *19.4.0477-4381030-20210525145957*
- Custom firmware version strings used by ISP in addition to the above: 
- RBI file name: 
- RBI official download URL: 
- Other RBI download links for us to look into it: 
- Raw bank dump download link: 
- Serial console bootlog: 
- Other potentially relevant info about this firmware version:

*repeat the same above block of info for each known version you heard about*

**Other details**

The model is similar to the DWA0120 seemingly the only difference between the 2 models is the lack of VOIP support on the DWA0120

**Comment by BonesMgee** [comment]
I followed the steps provided in #142 but in a firmware patch the ability to change `uci.ddns.service.@myddns_ipv4.ip_script` has been removed resulting in the error: `uci.ddns.service.@myddns_ipv4.ip_script: 9008 fault [ip_script is not writable]`

**Comment by LuKePicci** [comment]
@BonesMgee lats' continue discussing about this int #142, no need to open a second Model Support Issue for the same device.
