### ISSUE TITLE
Port Forwarding Issue

### ISSUE THREAD

**Issue by GusSuarez2** [hack-technicolor/hack-technicolor#277]
I have a Technicolor CGM4331COM Wireless Router via Xfinity. I’m contacting you directly cause their support team is useless. The router has been providing Internet access Flawlessly. My issue is with Port Forwarding.

I need to Forward two ports. 5445 for my DVR and 5253 for my Kohler Generator. Port 5445 opens with no problem. Port 5253 never opens. I test them with Open Port Check Tool.

The architecture set up is the following:
The DVR ethernet is connected directly to Technicolor Wireless Router.
The Kohler ethernet is connected directly to Technicolor Wireless Router.
A Google Wifi Router is connected directly to Technicolor Wireless Router. Then a 24 port switch to handle all the home internet needs.

Please help me try to open this 5253 port so I can avoid generator to server connection issues.

It has been a very frustrating experience dealing with Xfinity support team.

**Comment by kevdagoat** [comment]
Hi, best to ask your question on whirlpool forums, someone can help you over there :) https://forums.whirlpool.net.au/forum/82
